
#ifndef YX_CONFIG_Z_INDEX_H
#define YX_CONFIG_Z_INDEX_H

#include <limits.h>

enum yx_config_z_index {
    YX_CONFIG_Z_GROUP_BKGD    = INT_MIN,
    YX_CONFIG_Z_LAYER_BKGD    = 0,

    YX_CONFIG_Z_GROUP_MAIN    = 0,
    YX_CONFIG_Z_GROUP_FIGHTER = YX_CONFIG_Z_GROUP_MAIN,
    YX_CONFIG_Z_GROUP_WEAPON  = YX_CONFIG_Z_GROUP_MAIN,
    YX_CONFIG_Z_GROUP_BULLET  = YX_CONFIG_Z_GROUP_MAIN + 1,

    YX_CONFIG_Z_GROUP_FX      = 1,
    YX_CONFIG_Z_LAYER_FX      = 0,

    YX_CONFIG_Z_GROUP_DEBUG   = 1000,
};

#endif
