
#ifndef YX_CONFIG_COLLISION_GROUP_H
#define YX_CONFIG_COLLISION_GROUP_H

enum yx_config_collision_group {
    YX_CONFIG_COLLISION_GROUP_PLAYER_HP     = 1000,
    YX_CONFIG_COLLISION_GROUP_RIVAL_HP      = 2000,
    YX_CONFIG_COLLISION_GROUP_RIVAL_PATROL  = 3000,
    YX_CONFIG_COLLISION_GROUP_PLAYER_BULLET = 4000,
    YX_CONFIG_COLLISION_GROUP_RIVAL_BULLET  = 5000,
};

#endif
